<?xml version="1.0"?>

<!-- Core alphabet definitions for BioJava
   -
   - @author Matthew Pocock
   - @author Thomas Down 
  -->

<!DOCTYPE alphabetManager [
  <!ELEMENT alphabetManager (symbol|alphabet)*>
  <!ELEMENT symbol (description?)>
  <!ATTLIST symbol
    name	CDATA	#REQUIRED>

  <!ELEMENT description (#PCDATA)>

  <!ELEMENT alphabet (description?, (symbol|symbolref)*, characterTokenization*)>

  <!ATTLIST alphabet
    name ID #IMPLIED
    parent IDREF #IMPLIED>

  <!ELEMENT symbolref EMPTY>
  <!ATTLIST symbolref
    name	CDATA	#REQUIRED>
    
  <!ELEMENT characterTokenization ((atomicMapping|ambiguityMapping|gapSymbolMapping)*)>
  <!ATTLIST characterTokenization
   name CDATA #REQUIRED
   caseSensitive CDATA #REQUIRED>
   
  <!ELEMENT atomicMapping (symbolref)>
  <!ATTLIST atomicMapping 
   token CDATA #REQUIRED>
  <!ELEMENT ambiguityMapping (symbolref*)>
  <!ATTLIST ambiguityMapping 
   token CDATA #REQUIRED>
  <!ELEMENT gapSymbolMapping EMPTY>
  <!ATTLIST gapSymbolMapping
   token CDATA #REQUIRED>

]>

<alphabetManager>
  <symbol name="adenine">
    <description>pairs with T in DNA, and U in RNA</description>
  </symbol>

  <symbol name="guanine">
    <description>pairs with C</description>
  </symbol>

  <symbol name="cytosine">
    <description>pairs with G</description>
  </symbol>

  <symbol name="thymine">
    <description>pairs with A</description>
  </symbol>

  <symbol name="uracil">
    <description>pairs with A, replacing T in RNA</description>
  </symbol>

  <alphabet name="DNA">
    <description>Deoxy-Ribose Nucleic Acid. The stuff of life.</description>
    <symbolref name="adenine"/>
    <symbolref name="guanine"/>
    <symbolref name="cytosine"/>
    <symbolref name="thymine"/>
    
    <characterTokenization name="token" caseSensitive="false">
      <atomicMapping token="a">
        <symbolref name="adenine"/>
      </atomicMapping>

      <atomicMapping token="g">
        <symbolref name="guanine"/>
      </atomicMapping>

      <atomicMapping token="c">
        <symbolref name="cytosine"/>
      </atomicMapping>

      <atomicMapping token="t">
        <symbolref name="thymine"/>
      </atomicMapping>

      <ambiguityMapping token="r">
        <symbolref name="adenine" />
	<symbolref name="guanine" />
      </ambiguityMapping>

      <ambiguityMapping token="y">
        <symbolref name="cytosine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="m">
        <symbolref name="cytosine" />
	<symbolref name="adenine" />
      </ambiguityMapping>

      <ambiguityMapping token="k">
        <symbolref name="guanine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="s">
        <symbolref name="guanine" />
	<symbolref name="cytosine" />
      </ambiguityMapping>

      <ambiguityMapping token="w">
        <symbolref name="adenine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="h">
        <symbolref name="adenine" />
	<symbolref name="cytosine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="b">
        <symbolref name="guanine" />
	<symbolref name="cytosine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="v">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="cytosine" />
      </ambiguityMapping>

      <ambiguityMapping token="d">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="thymine" />
      </ambiguityMapping>
    
      <ambiguityMapping token="n">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="cytosine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="x">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="cytosine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="-">
        <!-- Gap is the empty set -->
      </ambiguityMapping>

      <!-- A gap by any other name would still smell so... gappy? -->
      
      <ambiguityMapping token=".">
      </ambiguityMapping>
      
      <ambiguityMapping token=" ">
      </ambiguityMapping>

      <gapSymbolMapping token="~" />>
    </characterTokenization>
  </alphabet>

  <alphabet name="RNA">
    <description>Ribose Nucleic Acid. Intermediate between genomic DNA and protein.</description>
    <symbolref name="adenine"/>	
    <symbolref name="guanine"/>
    <symbolref name="cytosine"/>
    <symbolref name="uracil"/>

    <characterTokenization name="token" caseSensitive="false">
      <atomicMapping token="a">
        <symbolref name="adenine"/>
      </atomicMapping>

      <atomicMapping token="g">
        <symbolref name="guanine"/>
      </atomicMapping>

      <atomicMapping token="c">
        <symbolref name="cytosine"/>
      </atomicMapping>

      <atomicMapping token="u">
        <symbolref name="uracil"/>
      </atomicMapping>

     <ambiguityMapping token="r">
        <symbolref name="adenine" />
	<symbolref name="guanine" />
      </ambiguityMapping>

      <ambiguityMapping token="y">
        <symbolref name="cytosine" />
	<symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="m">
        <symbolref name="cytosine" />
	<symbolref name="adenine" />
      </ambiguityMapping>

      <ambiguityMapping token="k">
        <symbolref name="guanine" />
	<symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="s">
        <symbolref name="guanine" />
	<symbolref name="cytosine" />
      </ambiguityMapping>

      <ambiguityMapping token="w">
        <symbolref name="adenine" />
	<symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="h">
        <symbolref name="adenine" />
	<symbolref name="cytosine" />
	<symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="b">
        <symbolref name="guanine" />
	<symbolref name="cytosine" />
	<symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="v">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="cytosine" />
      </ambiguityMapping>

      <ambiguityMapping token="d">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="n">
        <symbolref name="guanine" />
	    <symbolref name="adenine" />
	    <symbolref name="cytosine" />
	    <symbolref name="uracil" />
      </ambiguityMapping>
      
      <ambiguityMapping token="x">
        <symbolref name="guanine" />
	    <symbolref name="adenine" />
	    <symbolref name="cytosine" />
	    <symbolref name="uracil" />
      </ambiguityMapping>
      
      <ambiguityMapping token="-">
        <!-- Gap is the empty set -->
      </ambiguityMapping>

      <ambiguityMapping token=".">
      </ambiguityMapping>

      <gapSymbolMapping token="~" />>
    </characterTokenization>
  </alphabet>

  <alphabet name="NUCLEOTIDE">
    <description>All nucleic acids.</description>
    <symbolref name="adenine"/>
    <symbolref name="guanine"/>
    <symbolref name="cytosine"/>
    <symbolref name="thymine"/>
    <symbolref name="uracil"/>
    
    <characterTokenization name="token" caseSensitive="false">
      <atomicMapping token="a">
        <symbolref name="adenine"/>
      </atomicMapping>

      <atomicMapping token="g">
        <symbolref name="guanine"/>
      </atomicMapping>

      <atomicMapping token="c">
        <symbolref name="cytosine"/>
      </atomicMapping>

      <atomicMapping token="t">
        <symbolref name="thymine"/>
      </atomicMapping>

      <atomicMapping token="u">
        <symbolref name="uracil"/>
      </atomicMapping>
	  
      <ambiguityMapping token="r">
        <symbolref name="adenine" />
        <symbolref name="guanine" />
      </ambiguityMapping>

      <ambiguityMapping token="y">
        <symbolref name="cytosine" />
	    <symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="m">
        <symbolref name="cytosine" />
        <symbolref name="adenine" />
      </ambiguityMapping>

      <ambiguityMapping token="k">
        <symbolref name="guanine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="s">
        <symbolref name="guanine" />
	<symbolref name="cytosine" />
      </ambiguityMapping>

      <ambiguityMapping token="w">
        <symbolref name="adenine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="h">
        <symbolref name="adenine" />
	<symbolref name="cytosine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="b">
        <symbolref name="guanine" />
	<symbolref name="cytosine" />
	<symbolref name="thymine" />
      </ambiguityMapping>

      <ambiguityMapping token="v">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="cytosine" />
      </ambiguityMapping>

      <ambiguityMapping token="d">
        <symbolref name="guanine" />
	<symbolref name="adenine" />
	<symbolref name="thymine" />
      </ambiguityMapping>
    
      <ambiguityMapping token="n">
        <symbolref name="guanine" />
		<symbolref name="adenine" />
		<symbolref name="cytosine" />
	    <symbolref name="thymine" />
	    <symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="x">
        <symbolref name="guanine" />
	    <symbolref name="adenine" />
	    <symbolref name="cytosine" />
	    <symbolref name="thymine" />
	    <symbolref name="uracil" />
      </ambiguityMapping>

      <ambiguityMapping token="-">
        <!-- Gap is the empty set -->
      </ambiguityMapping>

      <ambiguityMapping token=".">
      </ambiguityMapping>

      <gapSymbolMapping token="~" />>
    </characterTokenization>
  </alphabet>

  <alphabet name="PROTEIN">
    <description>Unmodified Amino-acids commonly found in proteins</description>
    <symbol name="ALA">
    </symbol>

    <symbol name="ARG">
    </symbol>

    <symbol name="ASN">
    </symbol>

    <symbol name="ASP">
    </symbol>

    <symbol name="CYS">
    </symbol>

    <symbol name="GLN">
    </symbol>

    <symbol name="GLU">
    </symbol>

    <symbol name="GLY">
    </symbol>

    <symbol name="HIS">
    </symbol>

    <symbol name="ILE">
    </symbol>

    <symbol name="LEU">
    </symbol>

    <symbol name="LYS">
    </symbol>

    <symbol name="MET">
    </symbol>

    <symbol name="PHE">
    </symbol>

    <symbol name="PRO">
    </symbol>

    <symbol name="SER">
    </symbol>

    <symbol name="THR">
    </symbol>

    <symbol name="SEC">
    </symbol>

    <symbol name="TRP">
    </symbol>

    <symbol name="TYR">
    </symbol>

    <symbol name="VAL">
    </symbol>

    <characterTokenization name="token" caseSensitive="false">
      <atomicMapping token="A">
        <symbolref name="ALA" />
      </atomicMapping>

      <atomicMapping token="R">
        <symbolref name="ARG" />
      </atomicMapping>

      <atomicMapping token="N">
        <symbolref name="ASN" />
      </atomicMapping>

      <atomicMapping token="D">
        <symbolref name="ASP" />
      </atomicMapping>

      <atomicMapping token="C">
        <symbolref name="CYS" />
      </atomicMapping>

      <atomicMapping token="Q">
        <symbolref name="GLN" />
      </atomicMapping>

      <atomicMapping token="E">
        <symbolref name="GLU" />
      </atomicMapping>

      <atomicMapping token="G">
        <symbolref name="GLY" />
      </atomicMapping>
      
      <atomicMapping token="H">
        <symbolref name="HIS" />
      </atomicMapping>

      <atomicMapping token="I">
        <symbolref name="ILE" />
      </atomicMapping>

      <atomicMapping token="L">
        <symbolref name="LEU" />
      </atomicMapping>

      <atomicMapping token="K">
        <symbolref name="LYS" />
      </atomicMapping>

      <atomicMapping token="M">
        <symbolref name="MET" />
      </atomicMapping>

      <atomicMapping token="F">
        <symbolref name="PHE" />
      </atomicMapping>

      <atomicMapping token="P">
        <symbolref name="PRO" />
      </atomicMapping>

      <atomicMapping token="S">
        <symbolref name="SER" />
      </atomicMapping>

      <atomicMapping token="T">
        <symbolref name="THR" />
      </atomicMapping>

      <atomicMapping token="U">
        <symbolref name="SEC" />
      </atomicMapping>

      <atomicMapping token="W">
        <symbolref name="TRP" />
      </atomicMapping>

      <atomicMapping token="Y">
        <symbolref name="TYR" />
      </atomicMapping>

      <atomicMapping token="V">
        <symbolref name="VAL" />
      </atomicMapping>

      <ambiguityMapping token="X">
        <symbolref name="ALA"/>
        <symbolref name="ARG"/>
        <symbolref name="ASN"/>
        <symbolref name="ASP"/>
        <symbolref name="CYS"/>
        <symbolref name="GLN"/>
        <symbolref name="GLU"/>
        <symbolref name="GLY"/>
        <symbolref name="HIS"/>
        <symbolref name="ILE"/>
        <symbolref name="LEU"/>
        <symbolref name="LYS"/>
        <symbolref name="MET"/>
        <symbolref name="PHE"/>
        <symbolref name="PRO"/>
        <symbolref name="SER"/>
        <symbolref name="THR"/>
        <symbolref name="SEC"/>
        <symbolref name="TRP"/>
        <symbolref name="TYR"/>
        <symbolref name="VAL"/>
      </ambiguityMapping>

      <ambiguityMapping token="B">
        <symbolref name="ASP" />
	<symbolref name="ASN" />
      </ambiguityMapping>

      <ambiguityMapping token="Z">
        <symbolref name="GLU" />
	<symbolref name="GLN" />
      </ambiguityMapping>

      <ambiguityMapping token="-">
      </ambiguityMapping>

      <ambiguityMapping token=".">
      </ambiguityMapping>

      <gapSymbolMapping token="~" />>
    </characterTokenization>
  </alphabet>

  <alphabet name="PROTEIN-TERM" parent="PROTEIN">
    <symbol name="TER">
      <description>Termination signal during translation</description>
    </symbol>

    <!-- THOMASD we surely shouldn't need to replicated this -->

    <characterTokenization name="token" caseSensitive="false">
      <atomicMapping token="*">
        <symbolref name="TER" />
      </atomicMapping>

      <atomicMapping token="A">
        <symbolref name="ALA" />
      </atomicMapping>

      <atomicMapping token="R">
        <symbolref name="ARG" />
      </atomicMapping>

      <atomicMapping token="N">
        <symbolref name="ASN" />
      </atomicMapping>

      <atomicMapping token="D">
        <symbolref name="ASP" />
      </atomicMapping>

      <atomicMapping token="C">
        <symbolref name="CYS" />
      </atomicMapping>

      <atomicMapping token="Q">
        <symbolref name="GLN" />
      </atomicMapping>

      <atomicMapping token="E">
        <symbolref name="GLU" />
      </atomicMapping>

      <atomicMapping token="G">
        <symbolref name="GLY" />
      </atomicMapping>
      
      <atomicMapping token="H">
        <symbolref name="HIS" />
      </atomicMapping>

      <atomicMapping token="I">
        <symbolref name="ILE" />
      </atomicMapping>

      <atomicMapping token="L">
        <symbolref name="LEU" />
      </atomicMapping>

      <atomicMapping token="K">
        <symbolref name="LYS" />
      </atomicMapping>

      <atomicMapping token="M">
        <symbolref name="MET" />
      </atomicMapping>

      <atomicMapping token="F">
        <symbolref name="PHE" />
      </atomicMapping>

      <atomicMapping token="P">
        <symbolref name="PRO" />
      </atomicMapping>

      <atomicMapping token="S">
        <symbolref name="SER" />
      </atomicMapping>

      <atomicMapping token="T">
        <symbolref name="THR" />
      </atomicMapping>

      <atomicMapping token="U">
        <symbolref name="SEC" />
      </atomicMapping>

      <atomicMapping token="W">
        <symbolref name="TRP" />
      </atomicMapping>

      <atomicMapping token="Y">
        <symbolref name="TYR" />
      </atomicMapping>

      <atomicMapping token="V">
        <symbolref name="VAL" />
      </atomicMapping>

      <ambiguityMapping token="X">
        <symbolref name="ALA"/>
        <symbolref name="ARG"/>
        <symbolref name="ASN"/>
        <symbolref name="ASP"/>
        <symbolref name="CYS"/>
        <symbolref name="GLN"/>
        <symbolref name="GLU"/>
        <symbolref name="GLY"/>
        <symbolref name="HIS"/>
        <symbolref name="ILE"/>
        <symbolref name="LEU"/>
        <symbolref name="LYS"/>
        <symbolref name="MET"/>
        <symbolref name="PHE"/>
        <symbolref name="PRO"/>
        <symbolref name="SER"/>
        <symbolref name="THR"/>
        <symbolref name="SEC"/>
        <symbolref name="TRP"/>
        <symbolref name="TYR"/>
        <symbolref name="VAL"/>
      </ambiguityMapping>

      <ambiguityMapping token="X">
        <symbolref name="ALA"/>
        <symbolref name="ARG"/>
        <symbolref name="ASN"/>
        <symbolref name="ASP"/>
        <symbolref name="CYS"/>
        <symbolref name="GLN"/>
        <symbolref name="GLU"/>
        <symbolref name="GLY"/>
        <symbolref name="HIS"/>
        <symbolref name="ILE"/>
        <symbolref name="LEU"/>
        <symbolref name="LYS"/>
        <symbolref name="MET"/>
        <symbolref name="PHE"/>
        <symbolref name="PRO"/>
        <symbolref name="SER"/>
        <symbolref name="THR"/>
        <symbolref name="SEC"/>
        <symbolref name="TRP"/>
        <symbolref name="TYR"/>
        <symbolref name="VAL"/>
	<symbolref name="TER" />
      </ambiguityMapping>

      <ambiguityMapping token="B">
        <symbolref name="ASP" />
	<symbolref name="ASN" />
      </ambiguityMapping>

      <ambiguityMapping token="Z">
        <symbolref name="GLU" />
	<symbolref name="GLN" />
      </ambiguityMapping>

      <ambiguityMapping token="-">
      </ambiguityMapping>

      <ambiguityMapping token=".">
      </ambiguityMapping>

      <gapSymbolMapping token="~" />>
    </characterTokenization>

  </alphabet>

  <alphabet name="STRUCTURE">
    <symbol name="nothing">
      <description>The structure here is undetermined</description>
    </symbol>

    <symbol name="coil">
      <description>Random coil</description>
    </symbol>

    <symbol name="alpha-helix">
      <description>part of an alpha-helix</description>
    </symbol>

    <symbol name="3(10)-helix">
    </symbol>

    <symbol name="Pi-helix">
    </symbol>

    <symbol name="sheet">
      <description>part of an extended hydrogen bonded beta-strand (extended strand, logs of Bs)</description>
    </symbol>

    <symbol name="beta-bridge">
      <description>like a lone E</description>
    </symbol>

    <symbol name="turn">
    </symbol>

    <symbol name="bend">
      <description>five-residue bend centred at residue i</description>
    </symbol>

    <characterTokenization name="token" caseSensitive="false">
      <atomicMapping token=" ">
        <symbolref name="nothing" />
      </atomicMapping>

      <atomicMapping token="c">
        <symbolref name="coil" />
      </atomicMapping>

      <atomicMapping token="h">
        <symbolref name="alpha-helix" />
      </atomicMapping>

      <atomicMapping token="g">
        <symbolref name="3(10)-helix" />
      </atomicMapping>

      <atomicMapping token="i">
        <symbolref name="Pi-helix" />
      </atomicMapping>

      <atomicMapping token="e">
        <symbolref name="sheet" />
      </atomicMapping>

      <atomicMapping token="b">
        <symbolref name="beta-bridge" />
      </atomicMapping>

      <atomicMapping token="t">
        <symbolref name="turn" />
      </atomicMapping>

      <atomicMapping token="s">
        <symbolref name="bend" />
      </atomicMapping>

      <ambiguityMapping token="-">
      </ambiguityMapping>

      <gapSymbolMapping token="~" />>
    </characterTokenization>
  </alphabet>

</alphabetManager>

