=== CarmeloFoti/biojava/biojava3-aa-prop/doc/compounds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2011 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="molecular_formula">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="element" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="elements">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="element" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="element">
		<xs:complexType>
			<xs:attribute name="symbol" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="mono_isotopic_mass">
				<xs:simpleType>
					<xs:restriction base="xs:decimal"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="count">
				<xs:simpleType>
					<xs:restriction base="xs:byte"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="compounds">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="elements"/>
				<xs:element ref="amino_acids"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="amino_acids">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="amino_acid" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="amino_acid">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="molecular_formula"/>
			</xs:sequence>
			<xs:attribute name="symbol" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="A"/>
						<xs:enumeration value="C"/>
						<xs:enumeration value="D"/>
						<xs:enumeration value="E"/>
						<xs:enumeration value="F"/>
						<xs:enumeration value="G"/>
						<xs:enumeration value="H"/>
						<xs:enumeration value="I"/>
						<xs:enumeration value="K"/>
						<xs:enumeration value="L"/>
						<xs:enumeration value="M"/>
						<xs:enumeration value="N"/>
						<xs:enumeration value="P"/>
						<xs:enumeration value="Q"/>
						<xs:enumeration value="R"/>
						<xs:enumeration value="S"/>
						<xs:enumeration value="T"/>
						<xs:enumeration value="V"/>
						<xs:enumeration value="W"/>
						<xs:enumeration value="Y"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="short" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Ala"/>
						<xs:enumeration value="Arg"/>
						<xs:enumeration value="Asn"/>
						<xs:enumeration value="Asp"/>
						<xs:enumeration value="Cys"/>
						<xs:enumeration value="Gln"/>
						<xs:enumeration value="Glu"/>
						<xs:enumeration value="Gly"/>
						<xs:enumeration value="His"/>
						<xs:enumeration value="Ile"/>
						<xs:enumeration value="Leu"/>
						<xs:enumeration value="Lys"/>
						<xs:enumeration value="Met"/>
						<xs:enumeration value="Phe"/>
						<xs:enumeration value="Pro"/>
						<xs:enumeration value="Ser"/>
						<xs:enumeration value="Thr"/>
						<xs:enumeration value="Trp"/>
						<xs:enumeration value="Tyr"/>
						<xs:enumeration value="Val"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Alanine"/>
						<xs:enumeration value="Arginine"/>
						<xs:enumeration value="Asparagine"/>
						<xs:enumeration value="Aspartic Acid"/>
						<xs:enumeration value="Cysteine"/>
						<xs:enumeration value="Glutamic Acid"/>
						<xs:enumeration value="Glutamine"/>
						<xs:enumeration value="Glycine"/>
						<xs:enumeration value="Histidine"/>
						<xs:enumeration value="Isoleucine"/>
						<xs:enumeration value="Leucine"/>
						<xs:enumeration value="Lysine"/>
						<xs:enumeration value="Methionine"/>
						<xs:enumeration value="Phenylalanine"/>
						<xs:enumeration value="Proline"/>
						<xs:enumeration value="Serine"/>
						<xs:enumeration value="Threonine"/>
						<xs:enumeration value="Tryptophan"/>
						<xs:enumeration value="Tyrosine"/>
						<xs:enumeration value="Valine"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== CarmeloFoti/biojava/biojava3-aa-prop/doc/compounds.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
    Document   : dformula.xml
    Created on : April 12, 2010, 2:37 PM
    Author     : Scooter
    Description: Purpose of the document follows. Modifications tag is removed.
-->
<compounds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///Z:/Documents/Fu%20Work%20Data/GoogleWorkspace/biojava3-aa-prop/doc/compounds.xsd">
	<elements>
		<element symbol="C" mono_isotopic_mass="12.00000000000"/>
		<element symbol="H" mono_isotopic_mass="1.0078246"/>
		<element symbol="D" mono_isotopic_mass="2.0141021"/>
		<element symbol="N" mono_isotopic_mass="14.0030732"/>
		<element symbol="O" mono_isotopic_mass="15.9949141"/>
		<element symbol="P" mono_isotopic_mass="30.973762"/>
		<element symbol="S" mono_isotopic_mass="31.972070"/>
	</elements>
	<amino_acids>
		<amino_acid symbol="A" short="Ala" name="Alanine">
			<molecular_formula>
				<element symbol="C" count="3"/>
				<element symbol="H" count="5"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="R" short="Arg" name="Arginine">
			<molecular_formula>
				<element symbol="C" count="6"/>
				<element symbol="H" count="12"/>
				<element symbol="N" count="4"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="N" short="Asn" name="Asparagine">
			<molecular_formula>
				<element symbol="C" count="4"/>
				<element symbol="H" count="6"/>
				<element symbol="N" count="2"/>
				<element symbol="O" count="2"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="D" short="Asp" name="Aspartic Acid">
			<molecular_formula>
				<element symbol="C" count="4"/>
				<element symbol="H" count="5"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="3"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="C" short="Cys" name="Cysteine">
			<molecular_formula>
				<element symbol="C" count="3"/>
				<element symbol="H" count="5"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
				<element symbol="S" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="E" short="Glu" name="Glutamic Acid">
			<molecular_formula>
				<element symbol="C" count="5"/>
				<element symbol="H" count="7"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="3"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="Q" short="Gln" name="Glutamine">
			<molecular_formula>
				<element symbol="C" count="5"/>
				<element symbol="H" count="8"/>
				<element symbol="N" count="2"/>
				<element symbol="O" count="2"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="G" short="Gly" name="Glycine">
			<molecular_formula>
				<element symbol="C" count="2"/>
				<element symbol="H" count="3"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="H" short="His" name="Histidine">
			<molecular_formula>
				<element symbol="C" count="6"/>
				<element symbol="H" count="7"/>
				<element symbol="N" count="3"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="I" short="Ile" name="Isoleucine">
			<molecular_formula>
				<element symbol="C" count="6"/>
				<element symbol="H" count="11"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="L" short="Leu" name="Leucine">
			<molecular_formula>
				<element symbol="C" count="6"/>
				<element symbol="H" count="11"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="K" short="Lys" name="Lysine">
			<molecular_formula>
				<element symbol="C" count="6"/>
				<element symbol="H" count="12"/>
				<element symbol="N" count="2"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="M" short="Met" name="Methionine">
			<molecular_formula>
				<element symbol="C" count="5"/>
				<element symbol="H" count="9"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
				<element symbol="S" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="F" short="Phe" name="Phenylalanine">
			<molecular_formula>
				<element symbol="C" count="9"/>
				<element symbol="H" count="9"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="P" short="Pro" name="Proline">
			<molecular_formula>
				<element symbol="C" count="5"/>
				<element symbol="H" count="7"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="S" short="Ser" name="Serine">
			<molecular_formula>
				<element symbol="C" count="3"/>
				<element symbol="H" count="5"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="2"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="T" short="Thr" name="Threonine">
			<molecular_formula>
				<element symbol="C" count="4"/>
				<element symbol="H" count="7"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="2"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="W" short="Trp" name="Tryptophan">
			<molecular_formula>
				<element symbol="C" count="11"/>
				<element symbol="H" count="10"/>
				<element symbol="N" count="2"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="Y" short="Tyr" name="Tyrosine">
			<molecular_formula>
				<element symbol="C" count="9"/>
				<element symbol="H" count="9"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="2"/>
			</molecular_formula>
		</amino_acid>
		<amino_acid symbol="V" short="Val" name="Valine">
			<molecular_formula>
				<element symbol="C" count="5"/>
				<element symbol="H" count="9"/>
				<element symbol="N" count="1"/>
				<element symbol="O" count="1"/>
			</molecular_formula>
		</amino_acid>
	</amino_acids>
</compounds>
